name: "Auto Assign"
on:
  - pull_request_target

jobs:
  assign_reviewer:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'check-spelling'
    steps:
    - uses: jsoref/auto-assign-reviewer-by-files@HEAD
      with:
        config: '.github/assign-by-files.yml'
        token: ${{ secrets.GITHUB_TOKEN }}
